### ISSUE TITLE
前端vue代码缺失

### ISSUE THREAD

**Issue by Simon332** [danyuan-danyuan/danyuan-application#1]
您好看到您后台代码有缺失关于vue部分 你能上传最新版本的吗

**Comment by 514840279** [comment]
您好：
danyuan-application 虽然有计划做vue相关的代码，但是现阶段并没有开发所有页面展示的部分都在 danyuan-application-zuul-server中，danyuan-application-web-vue-elm并没有进行相关代码设计，如果想要vue版本的 adminLTE 页面可以参考下 vue-adminLTE




------------------ 原始邮件 ------------------
发件人: "Simon332"<notifications@github.com>;
发送时间: 2019年1月27日(星期天) 凌晨3:52
收件人: "danyuan-danyuan/danyuan-application"<danyuan-application@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [danyuan-danyuan/danyuan-application] 前端vue代码缺失 (#1)




您好看到您后台代码有缺失关于vue部分 你能上传最新版本的吗
